name: Auto Crawl Cafef Data
on:
  schedule:
    - cron: "0 18 * * *"  # 6PM hàng ngày (UTC)
  workflow_dispatch:
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas
      - name: Run Crawler
        run: |
          python crawl_carref.py || exit 1  # Stop if script fails
          ls -la  # Debug: Show generated files
      - name: Commit & Push Data
        if: success() && fileExists('foreign_net_values.csv')
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add foreign_net_values.csv
            git commit -m "Update foreign net values [auto]"
            git push
      - name: Debug - Check Files
        if: always()
        run: |
            echo "=== Current Directory ==="
            ls -la
            echo "=== CSV Contents ==="
            cat foreign_net_values.csv || echo "No CSV file found"
