name: Auto Crawl Cafef Data
on:
  schedule:
    - cron: "0 18 * * *"  # 6PM hàng ngày (UTC)
  workflow_dispatch:
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas
      - name: Run Crawler
        run: python crawl_cafef.py
      - name: Commit & Push Data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add foreign_net_values.csv
          git commit -m "Update foreign net values"
          git push
